### PR TITLE
chore: update to flutter2.0/sdk 2.12 - null safety

### PR DESCRIPTION
**Pull request by basti1253**
Hey Brian,

First of all thanks for your work! I've updated the codebase to support null safety. As I want to update my code base fast I thought a helping hand could be useful ;)

kind regards

Sebastian

### CODE REVIEW

**Comment by brianegan** [comment]
Yes, thanks for the contribution! I'm working my way through Redux stuff this week, please bear with me as there's a lot to do.

**Comment by brianegan** [comment]
Thanks so much! I'm going to drop the Flutter constraint and then publish (this library does not have any Flutter dependencies -- it's a pure Dart project :)

**Comment by brianegan** [comment]
Published 0.4.0 -- thanks again :)

**Comment by basti1253** [comment]
> I'm working my way through Redux stuff this week, please bear with me as there's a lot to do.

I didn't mean to put the pressure drop on you ;) 

> I'm going to drop the Flutter constraint 
Oops. Thanks ;) of course for the quick merge, too

**Pull request merged**
